### ISSUE TITLE
GuideGuide not working in OSX 10, Photoshop CC 2015

### ISSUE THREAD

**Issue by sqwear** [guideguide/support#165] opened 2015-07-10 23:04 UTC
I have followed the directions and place the GuideGuide folder in my Extensions folder. But when I open the GuideGuide panel it is blank.

![image](https://cloud.githubusercontent.com/assets/1722790/8630640/33c4bb80-271d-11e5-860a-897cbe6b36d0.png)

Here is my extensions folder

![image](https://cloud.githubusercontent.com/assets/1722790/8630645/4f429ab2-271d-11e5-9a8c-c9c1b825d717.png)

**Comment by cameronmcefee** [comment] 2015-07-10 23:39
Hi @sqwear,

There may be a couple reasons, but my guess is that it's one of the more common thing: Photoshop weirdness. I've had luck "fixing" it by waiting 30-40 seconds (you won't always have to do this), closing and reopening the panel window, and restarting my computer/photoshop.

If it still doesn't show up after that, let me know. Also, be sure the inside of that GuideGuide folder looks like this:

![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by Holloweaver** [comment] 2015-07-13 11:06
hi there, despite several restarts i'm still unable to use guideguide, not even the panel can be found within photoshop. unzipped folder 'guidguide' is in the place described... still love it because now i know what i'm missing... :(

**Comment by cameronmcefee** [comment] 2015-07-13 13:32
@Holloweaver would you mind creating a new issue so we can discuss your case separately? Please be detailed about what isn't working, in case the issue is unrelated.

**Comment by sqwear** [comment] 2015-07-14 18:01
BTW, I got mine working by right clicking the black area of the GuideGuide extension panel.. Select "View Source" then magically the extensions appeared.

**Comment by cameronmcefee** [comment] 2015-07-14 22:44
@sqwear Haha, wow… if that works reliably, that makes me think it might actually be something GuideGuide could trigger/fix. I'll have to look into that the next time it happens to me.

**Comment by cameronmcefee** [comment] 2015-12-09 20:22
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.

**Closed by cameronmcefee** 2015-12-09 20:22 UTC
