### ISSUE TITLE
Guide Guide v 3.1.4 not working in photoshop cc

### ISSUE THREAD

**Issue by shafeequemat** [guideguide/support#133] opened 2015-06-08 10:35 UTC
I have successfully installed guide guide v 3.1.4 to photoshop cc. But when I open the guide guide menu, I can't see any options of the extension. Only white color. I have attached a Picture refering the issue. please help me.
![untitled-1](https://cloud.githubusercontent.com/assets/12795832/8032972/2b7f6e4a-0df8-11e5-8e6c-a4bacc977ea4.jpg)

**Comment by cameronmcefee** [comment] 2015-06-08 15:32
Hi @shafeequemat,

Be sure you have the most current versions of both the Extension Manager and Photoshop CC. That problem existed in the earliest versions of Photoshop CC. This was most typically caused by GuideGuide trying to save data, because the first few versions of CC didn't support saving data.

![monosnap 2015-06-08 08-31-36](https://cloud.githubusercontent.com/assets/72919/8038511/c7befca2-0db8-11e5-8b86-6aa0549235b3.jpg)
![monosnap 2015-06-08 08-32-00](https://cloud.githubusercontent.com/assets/72919/8038518/d6d6c9c2-0db8-11e5-983c-0515c7f01304.jpg)

**Comment by cacaocom** [comment] 2015-06-22 09:08
I have the same problem tough usin adobe extension manager 7.3.2.39 and latest version of photoshop CC.. I see the extension in photoshop but when I try to use it I have the message : "the extension can not be loaded since it is not well signed"
![1](https://cloud.githubusercontent.com/assets/12997427/8278845/faab3e0c-18ce-11e5-8bc0-7653836f8aa8.jpg)

**Comment by cameronmcefee** [comment] 2015-12-09 20:22
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.

**Closed by cameronmcefee** 2015-12-09 20:22 UTC
