### ISSUE TITLE
CC 2015 on Mac, any action opens Units and Rulers preferences dialog... twice.

### ISSUE THREAD

**Issue by MaxJohnson** [guideguide/support#159] opened 2015-06-30 20:07 UTC
Set up Guide Guide on my boss' mac today, and am unable to add any guides or input text values.

If I add values to the fields or press any of the shortcut guide buttons, the Units and Rulers Photoshop Preferences dialog pops up with "Column Size: Width [180] [points]" highlighted. After I cancel out, it pops up one more time before returning to photoshop.

Even happens using the custom tab with notation.

I have pretty limited access to his machine, so the best I can do right now is say that he's running CC 2015 and followed the online instructions for Mac install.

No problems whatsoever on my PC running CC 2015

Any idea what could be happening?

**Comment by cameronmcefee** [comment] 2015-06-30 20:33
Hi @MaxJohnson,

Wow, that's quite the error. There's nothing about GuideGuide that should open that dialogue. 

> Units and Rulers Photoshop Preferences dialog pops up with "Column Size: Width [180] [points]" highlighted

We can rule this out as unrelated. That's the default state of that dialogue as far as I can tell.

I do notice that all the actions you mention trigger this are actions that involve checking the document info, a process which interacts briefly with the units and measurement settings via code (it switches your ruler from whatever it is to px and then back again). While there is no reason it should open that dialogue, I wonder if something strange is causing it to do so.

Any chance uninstalling and reinstalling GuideGuide resolves the issue? Given the unusual, and in my experience, unreproducable nature of the issue, I'm not sure I'll be able to have a fix any time soon if a reinstall doesn't fix it.

**Comment by MaxJohnson** [comment] 2015-06-30 20:39
Hi  @cameronmcefee,
Thank you for the quick response! Every computer is a beautiful and unique snow-f**k, so I'm not surprised. It's possible that a reboot or reinstall will fix it with magic.

I'll try a reinstall when I get a chance and report back. Due to the unusual and unpredictable nature of his machine, this may be a while.

Thanks again!

**Comment by cameronmcefee** [comment] 2015-06-30 22:04
> Every computer is a beautiful and unique snow-f**k

You made my day. Let me know what happens and I'll figure out what the next step is. I can tell you that this is a very unique case. I imagine it's not much consolation as far as solutions, but it is in the realm of things that shouldn't logically happen.

**Comment by cameronmcefee** [comment] 2015-06-30 22:04
Whoops, accidental close. Ignore that.

**Comment by MaxJohnson** [comment] 2015-07-03 04:24
Best to just close this out as user error. I won't be able to test any time soon and it's likely something specific to his computer, not a plugin issue. Thanks for your help!

**Comment by cameronmcefee** [comment] 2015-07-03 14:09
No worries! I think there's still the possibility to prevent it in the code but since I can preproduce it currently let's close this for now.

**Closed by cameronmcefee** 2015-07-03 14:09 UTC
