### ISSUE TITLE
Guideguide crashing CS6

### ISSUE THREAD

**Issue by tacoaallen** [guideguide/support#125] opened 2015-04-12 16:26 UTC
I downloaded guide guide about seven months ago and it was working perfectly, but suddenly this week it crashes photoshop every time I try to open it. I have CS6 on a 2012 Macbook pro with retina display. I have tried uninstalling and reinstalling it but that doesn't help.

**Comment by cameronmcefee** [comment] 2015-04-13 16:06
Hi @tacoaallen,

Did you update GuideGuide in that time, or did it just start crashing out of nowhere?

**Comment by tacoaallen** [comment] 2015-04-13 16:46
I haven't updated, it just started crashing last Monday

**Comment by cameronmcefee** [comment] 2015-04-14 00:21
Thanks for confirming. My suspicion around the cause depends on the version of GuideGuide that you are using. If you are using an older version, it might be a side effect of me closing down the update notification services for old versions, though that happened more than a week ago. If you use GuideGuide frequently, that's likely not the cause.

If you're up to date or you do use GuideGuide frequently, then most likely something on your system may have changed causing the issue.

In either case, check to make sure you're up to date (version 3.1.3 is the latest): http://guideguide.me/

**Comment by jducen** [comment] 2015-05-20 14:20
Hi,
Version 3.1.4 crashes CS6 on launch. Worked fine for months then yesterday the problems started.

**Comment by jducen** [comment] 2015-05-20 14:35
Installed 2.1.4, seems to work fine.

**Comment by cameronmcefee** [comment] 2015-05-20 18:04
That sounds about right @jducen. Please see https://github.com/guideguide/support/issues/115#issuecomment-75659528 for more info

**Closed by cameronmcefee** 2015-05-20 18:04 UTC

**Comment by jducen** [comment] 2015-05-20 19:25
Thank you.
