### ISSUE TITLE
Photoshop CC crashes when GuideGuide is run

### ISSUE THREAD

**Issue by 1markiz** [guideguide/support#102] opened 2015-01-11 15:53 UTC
My Photoshop CC crashes on any selected document when I want to make a grid with GuideGuide. I tried with advices given in previous threads (restarting, reinstalling, etc) and still got the crash. 

Here are the crash details:

**Photoshop version** http://prntscr.com/5r6omn
![8sfn51p](https://cloud.githubusercontent.com/assets/10487197/5695777/6a20e9a4-99b2-11e4-8e19-267ccb8fc211.png)

**Error screenshot** http://prntscr.com/5r6oxj
![mjxf5dc](https://cloud.githubusercontent.com/assets/10487197/5695778/6cefa45e-99b2-11e4-88e2-763607774963.png)

**OS: Windows 7**

Error info from Event log

**General**

Faulting application name: Photoshop.exe, version: 15.2.2.310, time stamp: 0x5480338c
Faulting module name: Photoshop.exe, version: 15.2.2.310, time stamp: 0x5480338c
Exception code: 0xc0000005

**Details**

+ System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-01-11T15:45:11.000000000Z 
 
   EventRecordID 102548 
 
   Channel Application 
 
   Computer Markiz-PC 
 
   Security 
 

- EventData 

   Photoshop.exe 
   15.2.2.310 
   5480338c 
   Photoshop.exe 
   15.2.2.310 
   5480338c 
   c0000005 
   00000000013ba34f 
   1c4 
   01d02db5653a7348 
   C:\Program Files\Adobe\Adobe Photoshop CC 2014\Photoshop.exe 
   C:\Program Files\Adobe\Adobe Photoshop CC 2014\Photoshop.exe 
   d30725e0-99a8-11e4-8524-681729413ee8

**Comment by 1markiz** [comment] 2015-01-11 15:57
GuideGuide works fine in Photoshop CS6, crashes only in CC. Just checked.

**Comment by cameronmcefee** [comment] 2015-01-13 16:27
Hi @1markiz,

Awesome report. That's super helpful. Doing some googling of the exception `0xc0000005` yields some [interesting results](http://www.updatexp.com/0xC0000005.html).

Since this is the first time I've had someone report this bug along with something concrete I could research, I'd appreciate if you could help me rule out the obvious (based on the article). Have you changed your RAM recently?

If that doesn't happen to be the cause, I'm not immediately aware of a solution unfortunately. I'm working on a UI update that may make the issue moot, but that's still a bit of a ways out. In the mean time, Photoshop CC 2014 now has a built in feature that is similar to GuideGuide that can be found at View > New Guide Layout.

And if you're technically curious, looking at the description it sounds like `0xc0000005` is an exception thrown when an application inappropriately accesses memory. From the screenshot I can tell that you likely committed an action that caused GuideGuide to ask Photoshop for document information. Unfortunately it's unclear whether it's GuideGuide or Photoshop that is the culprit. My hunch is that it's a Photoshop issue, but I don't really have anything to back that up. Since this issue only affects your system (and possibly a few others from similar reports) it's likely related to something with your particular configuration. If you've changed anything recently or have something unique about your system, that might be an area to investigate. You could also try out other free photoshop plugins to see if they cause similar problems.

**Comment by 1markiz** [comment] 2015-01-14 09:19
Hello @cameronmcefee 

I haven't changed RAM or any hardware recently, tho I have moved from Photoshop CS6 to CC. As soon as I installed GuideGuide (and that's basically only plugin I use) crashing started. I've noticed that CC also crashes when I try to create a document so I removed the GuideGuide to test will it crash then and it stopped. So yes, definitely the plugin is what causes the problem in my case.

Thanks for the advice on New Guide Layout. (y)

I'll try installing some other plugins and let you know if anything happens.

Thanks for the quick answer.
Marko

**Comment by 1markiz** [comment] 2015-01-14 09:28
@cameronmcefee I've tested couple other plugins (Flaticon and Tych panel) - no crashing.

**Comment by cameronmcefee** [comment] 2015-01-14 16:06
Thanks for testing that out, @1markiz. Would you mind trying a couple experiments for me to see if we can isolate the cause? 

### Background

The fact that it crashes upon creating a new document is an interesting development, as GuideGuide doesn't interact with that process in any way. The goal of this experiment is to determine if the new document is actually connected to the issue or is simply a catalyst to a less visible problem. My hypothesis is that the issue (if it's GuideGuide related) happens in the functions that run when you unfocus a field in GuideGuide, primarily checking the status of the document to do things like autofilling units and counting guides that will render.

In each experiment, please do any of the "before" actions first, then restart photoshop. This will ensure a clean slate for the experiment. If you are able to trigger a crash in a multistep experiement, please note at which point the crash happens. For example if it happens when you focus into a field vs when you unfocus a field, or when you click a button.

#### Experiment 1

Before: Close the GuideGuide panel if it's open, restart.

Test: When Photoshop opens, create a new document.

#### Experiment 2

Before: Open GuideGuide, restart Photoshop (so GuideGuide should be open when it restarts).

Test: Without touching GuideGuide, create a new document

#### Experiment 3

Before: Make sure GuideGuide is open, restart Photoshop (so GuideGuide should be open when it restarts).

Test: Click on one of GuideGuide's fields so that it focuses. Open a new document.

*(You can discontinue the experiments if you've been able to cause a crash in the previous experiments)*

#### Experiment 4

Before: Make sure GuideGuide is open, restart Photoshop (so GuideGuide should be open when it restarts).

Test: Click on one of GuideGuide's fields so that it focuses. Type something appropriate into the field. Open a new document.

**Comment by Dragoy** [comment] 2015-01-15 01:20
Hi, I have a similar problem. I have done the above points, there is no result. 
Error log (for Windows Logs): http://pastebin.com/M7Dy8B7X
Video (Crash photoshop): http://take.ms/qdwte

p.s: Sorry for my bad English language.

**Comment by 1markiz** [comment] 2015-01-15 09:41
@cameronmcefee When I left first comment here I deactivated GuideGuide through the Extension manager so I can use PS without crashing. Interesting thing is after I saw your last comment, I activated GuideGuide once again and Photoshop CC didn't crash even once. 

I've tried all of your experiments, no crashing.

Thanks for help, I'll write again if problem comes back.

**Comment by cameronmcefee** [comment] 2015-01-15 18:48
@1markiz I'm glad to hear it!

@Dragoy can you try uninstalling and reinstalling GuideGuide?

**Comment by Dragoy** [comment] 2015-01-17 15:39
@cameronmcefee I did it, but remained Problem.

**Comment by Dragoy** [comment] 2015-01-25 22:27
@cameronmcefee help me!

**Comment by cameronmcefee** [comment] 2015-02-05 23:41
Hi @Dragoy,

I'm sorry for the delayed reply. Unfortunately I don't think this is a problem I will be able to fix. In this scenario a Photoshop crash, as far as I can tell, indicates a Photoshop problem rather than one with GuideGuide. I would suggest that if you can get some sort of crash report that you submit it to Adobe, however I don't expect that will result in a quick solution for you.

You can try installing an [old version of GuideGuide (2.1.4)](http://guideguide.me/versions/) which may still work for you on Photoshop CC, or if you have the option of using Photoshop CC 2014 it has a new feature at View > New Guide Layout that works similarly to GuideGuide.

**Closed by cameronmcefee** 2015-02-05 23:41 UTC
