### ISSUE TITLE
GuideGuide opens then suddenly closes

### ISSUE THREAD

**Issue by Adrianna406** [guideguide/support#176] opened 2015-08-01 22:48 UTC
Hi There,

I have installed guideguide as an extension for Photoshop cc 2015. But whenever I execute it, it opens for about 1 second then suddenly closes. 

I have installed it under this directory:

C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\GuideGuide

What could be wrong?

**Comment by cameronmcefee** [comment] 2015-08-02 01:44
Hi @Adrianna406,

Does the UI ever load, or does the panel appear blank and then close?

**Comment by Adrianna406** [comment] 2015-08-02 09:09
Hi Cameronmcefee,

Like below: 
![image](https://cloud.githubusercontent.com/assets/13605153/9025487/7431a5d2-38fe-11e5-897f-9b4e578bb0bb.png)

It opens up blank, then closes.

**Comment by cameronmcefee** [comment] 2015-08-02 15:14
Hmm, ok. Typically when GuideGuide (the panel itself) breaks, it simply fails to load it's UI. Closing the panel altogether tends to indicate a problem that's related to Photoshop, or to the installed files. Here's a couple things to try:

- Check the Creative Cloud Application Manager to make sure Photoshop is up to date.

- Reinstall GuideGuide:

  1. Open the folder where you installed GuideGuide and delete it. Relaunch Photoshop and confirm that GuideGuide no longer appears at Window > Extensions > GuideGuide. You might see it flash a second before disappearing, similar to the issue you're experiencing. Once you've confirmed that GuideGuide isn't there, exit Photoshop. If it does still appear after deleting the GuideGuide files, let me know.

  1. Redownload GuideGuide and install as directed

  1. Launch Photoshop, and launch GuideGuide from Window > Extensions > GuideGuide

  1. Let me know what happens.

**Comment by Adrianna406** [comment] 2015-08-02 17:13
My Photoshop is up to date.

I reinstalled GuideGuide, but I haven't been able to directly unzip my files in this directory:

Windows 64: C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\
I received this error message.
![image](https://cloud.githubusercontent.com/assets/13605153/9027027/a973a66c-393c-11e5-9ad9-39262e9db912.png)

So I unzipped it in my "Documents" and copy and pasted the files into the above directory. It's still opening up blank :( and closing.

**Comment by cameronmcefee** [comment] 2015-08-02 21:00
Bummer! I'm unfortunately out of ideas.

Can you provide a screenshot of the file tree which shows the GuideGuide folder opened?

Can you also let me know which version of Windows you are using?

**Comment by Adrianna406** [comment] 2015-08-02 21:39
That is unfortunate!

I am using Windows 7.

![image](https://cloud.githubusercontent.com/assets/13605153/9028172/3b1c716e-3967-11e5-9978-b7dfb01b1e83.png)

**Comment by cameronmcefee** [comment] 2015-08-03 15:43
:-/ I was hoping there'd be something obvious with the folders that stands out, but sadly that is not the case. I was also hoping you might be on some bleed-edge release of Windows that would be patched in the future, but Windows 7 has definitely been confirmed to work.

Here are a few things to try if you're desperate. However, I have no idea if these will fix anything, so make your own judgment as to whether their side effects are worth the effort:

- Reset Photoshop's preferences. I'm not sure if that's still a thing with CC, but it used to solve some of the weird unknown problems in the CS days.

- Reinstall Photoshop. This probably works mostly because it resets the preferences, but since it resets *everything*, it usually fixes things.

- Talk to Adobe. I can't say that I've ever heard that this has been helpful, but hey, you always have to have a last resort.

**Comment by cameronmcefee** [comment] 2015-08-26 22:50
Someone else has confirmed (at least in their case) that reinstalling Photoshop resolves the issue.

**Comment by cameronmcefee** [comment] 2015-12-09 20:22
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.

**Closed by cameronmcefee** 2015-12-09 20:22 UTC
